/motion_capture_tracking:
  ros__parameters:
    type: optitrack
    hostname: 192.168.1.127
    mode: motionCapture
    topics:
      poses:
        qos:
          mode: sensor
          deadline: 50.0
    marker_configurations:
      default:
        offset:
        - 0.0
        - 0.0
        - 0.0
        points:
          p0:
          - 0.0
          - 0.0
          - 0.022
          p1:
          - -0.042
          - 0.042
          - 0.0
          p2:
          - -0.042
          - -0.042
          - 0.0
          p3:
          - 0.042
          - -0.042
          - 0.0
      default_single_marker:
        offset:
        - 0.0
        - -0.01
        - -0.04
        points:
          p0:
          - 0.0177184
          - 0.0139654
          - 0.0557585
      mocap_deck:
        offset:
        - 0.0
        - 0.0
        - -0.01
        points:
          p0:
          - 0.03
          - 0.0
          - 0.0
          p1:
          - 0.0
          - -0.03
          - 0.0
          p2:
          - -0.015
          - 0.0
          - 0.0
          p3:
          - 0.0
          - 0.03
          - 0.0
      medium_frame:
        offset:
        - 0.0
        - 0.0
        - -0.03
        points:
          p0:
          - -0.00896228
          - -0.000716753
          - 0.0716129
          p1:
          - -0.0156318
          - 0.0997402
          - 0.0508162
          p2:
          - 0.0461693
          - -0.0881012
          - 0.0380672
          p3:
          - -0.0789959
          - -0.0269793
          - 0.0461144
      big_frame:
        offset:
        - 0.0
        - 0.0
        - -0.06
        points:
          p0:
          - 0.0558163
          - -0.00196302
          - 0.0945539
          p1:
          - -0.0113941
          - 0.00945842
          - 0.0984811
          p2:
          - -0.0306277
          - 0.0514879
          - 0.0520456
          p3:
          - 0.0535816
          - -0.0400775
          - 0.0432799
      custom:
        offset:
        - 0.0
        - 0.0
        - 0.0
        points:
          p0:
          - 0.00404364
          - -0.003819084
          - 0.044847263
          p1:
          - 0.053301559
          - -0.005241718
          - 0.003299543
          p2:
          - -0.006209561
          - 0.005279079
          - 0.052425991
          p3:
          - -0.050273491
          - -0.001628632
          - 0.005699012
          p4:
          - -0.00086215
          - 0.015968507
          - -0.001419829
    dynamics_configurations:
      default:
        max_velocity:
        - 2
        - 2
        - 3
        max_angular_velocity:
        - 20
        - 20
        - 10
        max_roll: 1.4
        max_pitch: 1.4
        max_fitness_score: 0.001
    rigid_bodies:
      cf231:
        initial_position:
        - 0.0
        - 0.0
        - 0.0
        marker: custom
        dynamics: default
